# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_institucion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_crud_contenidos', 'Can do crud for contents'),)},
        ),
    ]
