# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0005_auto_20170607_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingPagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('paginas_confianza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.PaginaDeConfianza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.UserProfile')),
            ],
        ),
    ]
