# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0006_ratingpagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paginas_confianza',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_ratings',
            field=models.ManyToManyField(to='buscador.RatingPagina'),
        ),
    ]
