# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0007_auto_20170611_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingpagina',
            old_name='paginas_confianza',
            new_name='pagina_confianza',
        ),
    ]
