# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0010_auto_20170620_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='contenidos',
            field=models.ManyToManyField(to='buscador.Contenido'),
        ),
    ]
