# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0011_auto_20170620_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='busqueda',
            field=models.CharField(default='', max_length=200),
        ),
    ]
