# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0012_contenido_busqueda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_buscado', models.CharField(max_length=100)),
                ('fecha_busqueda', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
