# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0013_busqueda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
