# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0014_auto_20170702_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='tags',
        ),
        migrations.AddField(
            model_name='contenido',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buscador.Tag'),
            preserve_default=False,
        ),
    ]
